config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" ,registrations: 'registrations' }
  
  resources :search, only: [:index]

  root 'login#welcome'
  
  resources :posts do
  	collection do
  		get :wear
  		get :eat
  		get :live
  		get :culture
      get :about
      get :search
  	end
    member do
      put :archive
      delete :delete_archive
    end
  end

  resources :users do
    collection do
      get :show
    end
  end



  post 'posts/wear'
  post 'posts/eat'
  post 'posts/live'
  post 'posts/culture'
  post 'posts/about'
  post 'posts/search'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ActiveRecord::Base
  belongs_to :user
  belongs_to :post, counter_cache: :users_count
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
  
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	#attr_accessible :body, :title
  	belongs_to :user
  	has_many :archives
  	has_many :archiving_users, :through => :archives, :source => :user
  	enum category: [ :wear, :eat, :live, :culture]
  	enum season: [ :spring, :summer, :autumn, :winter]
  	#multisearchable :against => [:body, :title]
  	include PgSearch
  	
  pg_search_scope :search, against: [:title, :content], :using => {:tsearch => { :prefix => true}}
  


	def self.perform_search(keyword)
		if keyword.present?
     then Post.search(keyword)
		else Post.all
		end.sort
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  before_save :default_values
  has_many :posts
  has_many :archives
  has_many :archived_posts, :through => :archives , :source => :post
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]


  def default_values
  	self.is_editor ||= 0
  end

  def self.find_for_facebook_oauth(auth)
  user = where(provider: auth[:provider], uid: auth[:uid]).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
  end

  # 이 때는 이상하게도 after_create 콜백이 호출되지 않아서 아래와 같은 조치를 했다.
  # user.add_role :user if user.roles.empty?
  user   # 최종 반환값은 user 객체이어야 한다.
  end

  def already_archived?(post)
    #self.archives.find(:all, :conditions => ['post_id = ?',post_id]).size > 0
    Archive.where(:post_id => post.id).size > 0
  end


  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	def welcome
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only:[ :edit, :update, :destory]
 	before_action :set_post, only: [ :show, :edit, :update, :destroy, :archive,  :delete_archive]
 	

 	# def search
  #   	@posts = Post.search(params[:query])
  # 	end

	def index
		if params[:query].present?
		  @posts = Post.perform_search(params[:query])
		else
		  @posts = Post.all
		end
	end

 	def wear
 		@posts = Post.wear
 	end

 	def eat
 		@posts = Post.eat
 	end

 	def live
 		@posts = Post.live
 	end

 	def culture
 		@posts = Post.culture
 	end

 	def show
 	end
 
 	def new
 		@post = Post.new
 	end
 
 	def create
 		@post = Post.new(post_params)
 		@post.user = current_user
 		if @post.save
 			redirect_to @post
 		else
 			render 'new'
 		end
 	end
 
 	def update 
 		if @post.update(post_params)
 			redirect_to @post
 		else
 			render 'edit'
 		end
 	end
 
 	def destroy
 		@post.destroy
 		redirect_to posts_path
 	end

 	# 좋아요 기능 추가
 	def archive
 		Archive.create(post: @post, user: current_user)
 		flash[:success] = "Like Counted!"
 		redirect_to @post
 	end

 	#좋아요 취소
 	def delete_archive
 		@archive = Archive.find_by(:user_id => current_user.id)
 		@archive.destroy
 		redirect_to @post
 	end

 
 	private
 
 	def post_params
 		params.require(:post).permit(:title,:content,:image,:category,:season)
 	end
 
 	def set_post
 		@post = Post.find(params[:id])
 	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
    #params[:is_editor] = 1
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
 def index
   if params[:query].present?
     gifts = Post.search(params[:query])
   else
     @gifts = Post.all
   end
 end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  	@user = current_user
  	@posts = @user.archived_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_application_paste.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Letter</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'style'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


<div id="menu">
    <div class="close"></div>
</div>
<div class="btn">
</div>

<script>
   $(".btn").click(function() {$("#menu").addClass("open"); }); $(".close").click(function() {$("#menu").removeClass("open"); });
</script>

  <body>
   <%= render 'layouts/navbar'  %>
    <div style="text-align:center"><h3><strong><%= link_to "LETTER", root_url%></strong></h3></div> 
	<%= yield %>
</body>
</html>

app/views/layouts/_navbar.html.erb
 <!--    <nav class="navbar navbar-default">
         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-left">

         <% if user_signed_in? %>
           <li><%= link_to "Log-out", destroy_user_session_path, method: :delete %></li>
         <% else %>
           <li><%= link_to "Log-in", new_user_session_path %></li>
         <% end %>
       </ul>
    </div>
    <a class="navbar-brand"><%= image_tag('letter_logo.jpg',style: ' margin: auto; width:40px; height:40px; position:relative; bottom:8px')%></a> 
  </nav>
 -->
 <!-- first navbar -->
    <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
            <li class="sidebar-brand">
                <a href="#top" onclick=$("#menu-close").click();>Letter menu</a>
            </li>
            <li>
                <%= link_to "Home", root_path %>
            </li>
            <li>
              <%= link_to "About", posts_about_path %>
            </li>
            <li>
              <%= link_to "의", posts_wear_path %>
            </li>
            <li>
              <%= link_to "식", posts_eat_path %>
            </li>
            <li>
              <%= link_to "주", posts_live_path %>
            </li>
            <li>
              <%= link_to "락", posts_culture_path %>
            </li>
   
            <% if user_signed_in? %>
               <li><%= link_to "로그아웃", destroy_user_session_path, method: :delete %></li>
               <li><%= link_to "좋아요한 글", users_show_path %></li>
             <% else %>
               <li><%= link_to "로그인", new_user_session_path %></li>
            <% end %>

        </ul>
    </nav>
 
    <nav class="navbar  navbar-custom" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <ul class="nav navbar-nav navbar-left">
                  <%= form_tag posts_path, method: :get do %>
                  <%= text_field_tag :query, params[:query] %>
                  <%= submit_tag "GO", name: nil %>
                  <% end %>
               </ul>
            </div>

            <ul class="navbar-brand"><%= link_to image_tag('letter_logo.jpg',style: ' margin: auto; width:80px; height:80px; position:relative; bottom:50px'),root_path%></ul> 
      
    </nav> 

 
<!--         <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= image_tag(current_user.image, size: '20x20', style:'border-radius:3px;vertical-align:top;') if current_user.image %>
                <%= current_user.name %>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Profile", edit_user_registration_path %></li>
              </ul>
            </li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign in
               <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "with Auth Blog", new_user_session_path %></li>
                <li><%= link_to "with Facebook", user_facebook_omniauth_authorize_path(:facebook) %></li>
              </ul>
            </li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <p><%= link_to "로그아웃", destroy_user_session_path, method: :delete, data: {confirm: "Are you sure?" }, class: 'btn btn-default'%></p>
        <% else %>
          <p><%= link_to "로그인", new_user_session_path, class: 'btn btn-default' %></p>
          <p><%= link_to "페이스북으로 로그인", user_facebook_omniauth_authorize_path(:facebook) %></p>
        <% end %>

 -->
     <script>
    // Closes the sidebar menu
    $("#menu-close").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#],[data-toggle],[data-target],[data-slide])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    //#to-top button appears after scrolling
    var fixed = false;
    $(document).scroll(function() {
        if ($(this).scrollTop() > 250) {
            if (!fixed) {
                fixed = true;
                // $('#to-top').css({position:'fixed', display:'block'});
                $('#to-top').show("slow", function() {
                    $('#to-top').css({
                        position: 'fixed',
                        display: 'block'
                    });
                });
            }
        } else {
            if (fixed) {
                fixed = false;
                $('#to-top').hide("slow", function() {
                    $('#to-top').css({
                        display: 'none'
                    });
                });
            }
        }
    });
    // Disable Google Maps scrolling
    // See http://stackoverflow.com/a/25904582/1607849
    // Disable scroll zooming and bind back the click event
    var onMapMouseleaveHandler = function(event) {
        var that = $(this);
        that.on('click', onMapClickHandler);
        that.off('mouseleave', onMapMouseleaveHandler);
        that.find('iframe').css("pointer-events", "none");
    }
    var onMapClickHandler = function(event) {
            var that = $(this);
            // Disable the click handler until the user leaves the map area
            that.off('click', onMapClickHandler);
            // Enable scrolling zoom
            that.find('iframe').css("pointer-events", "auto");
            // Handle the mouse leave event
            that.on('mouseleave', onMapMouseleaveHandler);
        }
        // Enable map zooming with mouse scroll when the user clicks the map
    $('.map').on('click', onMapClickHandler);
    </script>

<!-- 

 <nav class="navbar navbar-default">
   <div class="container-fluid">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <a class="navbar-brand" href="#">Brand</a>
     </div>
 

     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
       <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
           <li><%= link_to "로그아웃", destroy_user_session_path, method: :delete %></li>
         <% else %>
           <li><%= link_to "로그인", new_user_session_path %></li>
         <% end %>
       </ul>
     </div>
   </div>
 </nav> -->

app/views/login/welcome.html.erb
<!-- 
<%= image_tag("culture.jpg") %>


<%#= image_tag('eat.JPG' ,style: 'display: block; margin: auto; width: 90%;') %>

<%#= link_to image_tag('image/someimage.png') + "Some text", some_path %>

 
<%= link_to image_tag('wear.JPG' ,style: ' margin: auto;  width: 49%;'), posts_wear_path %>
<%= link_to image_tag('eat.JPG' ,style: ' margin: auto; width: 49%;'), posts_eat_path %>
<%= link_to image_tag('live.JPG' ,style: ' margin: auto; width: 49%;'), posts_live_path %>
<%= link_to image_tag('culture.JPG' ,style: ' margin: auto; width: 49%;'), posts_culture_path %>

<%#= link_to "식", posts_eat_path, class: "btn btn-default" %>
<%#= link_to "주", posts_live_path, class: "btn btn-default" %>
<%#= link_to "락", posts_culture_path, class: "btn btn-default" %>
 -->

 <!DOCTYPE html>
<html lang="en">

<body>

    <!-- Header -->
<!--     <header id="top" class="header">
        <div class="text-vertical-center">
            <h1>Letter</h1>
            <h3>The Temperature in Our Nature</h3>
            <br>
            <a href="#about" class="btn btn-dark btn-lg">Find Out More</a>
        </div>
    </header> -->

    <!-- About -->

        <!-- /.container -->
    </section>
        <section id="portfolio" class="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h2>LIFE</h2>
                    <hr class="small">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="portfolio-item">
                                <a href="#">
                                    <%= link_to image_tag('wear.JPG', :class => "img-portfolio img-responsive"), posts_wear_path%>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="portfolio-item">
                                <a href="#">
                                    <%= link_to image_tag('eat.JPG', :class => "img-portfolio img-responsive" ), posts_eat_path%>
                                      </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="portfolio-item">
                                <a href="#">
                                    <%= link_to image_tag('live.JPG', :class => "img-portfolio img-responsive" ), posts_live_path%>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="portfolio-item">
                                <a href="#">
                                    <%= link_to image_tag('portfolio-4.jpg', :class => "img-portfolio img-responsive" ), posts_culture_path%>
                                </a>
                            </div>
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                    <a href="#" class="btn btn-dark">View More Items</a>
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>
    <!-- Services -->
    <!-- The circle icons use Font Awesome's stacked icon classes. For more information, visit http://fontawesome.io/examples/ -->
    


    <!-- Call to Action -->
    <aside class="call-to-action bg-primary">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>Give your letter to us</h3>
                    <a href="#" class="btn btn-lg btn-light">Click Me!</a>
                    
                </div>
            </div>
        </div>
    </aside>

    <!-- Map -->
    <section id="contact" class="map">
        <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12664.33398046273!2d126.9976306!3d37.482356!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x8e7b98f09038401d!2z7Jik7ZSI7Lus66as7KeA!5e0!3m2!1sko!2skr!4v1479241048357"></iframe>
        <br />
        <small>
            <a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A"></a>
        </small>
        </iframe>
    </section>

    <!-- Footer -->


</body>

</html>

app/views/posts/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	    	 <%= simple_form_for @post do |f| %>
			    <%= f.input :category, collection: Post.categories.keys, input_html: { :style=> 'width: 100px'} %>
			    <%= f.input :season, collection: Post.seasons.keys, input_html: { :style=> 'width: 100px'} %>
			    <h4>Title</h4>
			    <%= f.text_field :title%>
			    <br></br>
			    <%= f.cktext_area :content %>
			  	<%= f.submit %>
			 <% end %>
			<br></br>
        </div>
    </div>
    <!-- /.row -->
</div>

app/views/posts/_index_form.html.erb
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                	<% @posts.each do |post| %>
                    <h2><%= link_to post.title, post, class: "post-prieview post-title" %></h2>
                    <h3><%= post.content[0..100].html_safe%></h3>
                    <hr width=100%>
                    <% end %>
           			<br></br>
           			<% if user_signed_in? && current_user.is_editor %>
						<%= link_to "새 글 작성하기", new_post_path %>
					<% end %>
					<br></br><br></br>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->

      


<!--   
<table class="table table-striped">
	<thead>
		<tr>
			<th>제목</th>
			
		</tr>
	</thead>
	<tbody>
		<% @posts.each do |post| %>
				<tr>
						<td><%= link_to post.title, post%>
				</tr>
		<% end %>
	</tbody>c
</table> -->

app/views/posts/culture.html.erb
<section id="about" class="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>락</h2>
                <p class="lead">The Temperature in Our Nature </p>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>
<%= render 'posts/index_form' %>

app/views/posts/eat.html.erb
<section id="about" class="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>식</h2>
                <p class="lead">The Temperature in Our Nature </p>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>
<%= render 'posts/index_form' %>

app/views/posts/index.html.erb
<%= render 'posts/index_form' %>

app/views/posts/search.html.erb
<%= form_tag posts_path, method: :get do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "GO", name: nil %>
<% end %>

app/views/posts/show.html.erb
    <section id="about" class="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                	<h3><%=@post.title%></h3>
					<h5 style="text-align:right"><%=@post.created_at%></h5>
					<p><%= @post.content.html_safe%></p>


					<!-- 좋아요 기능 추가 -->
					<% if current_user.already_archived?(@post) %>
						<%= link_to delete_archive_post_path(@post), method: 'delete' do %>
						like
						<%= @post.users_count %>
						<%end%>
					<% else %>
						<%= link_to archive_post_path(@post), method: 'put' do %>
						like
						<%= @post.users_count %>
						<%end%>		
					<%end%>

					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


					<% if user_signed_in? && current_user.is_editor %>
						<%= link_to "편집 | ", edit_post_path %>
						<%= link_to "삭제 |", post_path,
									method: :delete,
									data: {confirm: 'Are you sure?'} %>
						<% if @post.category == 'wear' %>
							<%= link_to "목록", posts_wear_path %>
						<% elsif @post.category == 'eat' %>
							<%= link_to "목록", posts_eat_path %>
						<% elsif @post.category == 'live' %>
							<%= link_to "목록", posts_live_path %>
						<% elsif @post.category == 'culture' %>
							<%= link_to "목록", posts_culture_path %>
						<%end%>

					<% else %>
						<% if @post.category == 'wear' %>
							<%= link_to "목록", posts_wear_path %>
						<% elsif @post.category == 'eat' %>
							<%= link_to "목록", posts_eat_path %>
						<% elsif @post.category == 'live' %>
							<%= link_to "목록", posts_live_path %>
						<% elsif @post.category == 'culture' %>
							<%= link_to "목록", posts_culture_path %>
						<%end%>

					<% end %>

                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

<!-- 좋아요 기능 추가  -->